import { getFromLocalStorage } from "./helpers";
import emailjs from '@emailjs/browser';


const EMAILJS_SERVICE_ID = 'service_ijfqabe'; 
const EMAILJS_TEMPLATE_ID = 'template_g2df3sx'; 
const EMAILJS_PUBLIC_KEY = 'WbYaPBT4c9jzjHuXa';
const ALERT_EMAIL = 'armia.joseph35@gmail.com';

// Initialize EmailJS
if (typeof window !== 'undefined') {
    emailjs.init(EMAILJS_PUBLIC_KEY);
}

const SUSPICIOUS_PATHS = [
    'passwords',
    'backup',
    'config',
    'database',
    'db',
    'secret',
    'secrets',
    'env',
    '.env',
    'credentials',
    'api-keys',
    'private',
    'confidential',
    'internal',
    'login.php',
    'admin.php',
    'wp-admin',
    'wp-login',
    'phpinfo',
    'phpmyadmin',
    'mysql',
    'ssh',
    'ftp',
    'telnet',
    'root',
    'passwd',
    'shadow',
    'backup.sql',
    'dump.sql',
    '.git',
    '.svn',
    '.htaccess',
    '.htpasswd',
    'web.config',
    'server.key',
    'private.key',
    'id_rsa',
    'id_dsa',
];

// Decode JWT token (basic implementation without verification)
export function decodeJWT(token: string): any {
    try {
        const base64Url = token.split('.')[1];
        const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
        const jsonPayload = decodeURIComponent(
            atob(base64)
                .split('')
                .map(c => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2))
                .join('')
        );
        return JSON.parse(jsonPayload);
    } catch (error) {
        return null;
    }
}

// Get client IP (note: in frontend, we can only get this from headers or backend)
export async function getClientIP(): Promise<string> {
    try {
        // Try to get IP from a public API
        const response = await fetch('https://api.ipify.org?format=json');
        const data = await response.json();
        return data.ip;
    } catch (error) {
        // Fallback: return 'unknown' if we can't get the IP
        return 'unknown';
    }
}

// Check if a path is suspicious
export function isSuspiciousPath(path: string): boolean {
    const normalizedPath = path.toLowerCase();
    return SUSPICIOUS_PATHS.some(suspiciousPath => 
        normalizedPath.includes(suspiciousPath)
    );
}

// Get security alert payload
export async function getSecurityAlertPayload(path: string) {
    const token = getFromLocalStorage('token');
    const username = getFromLocalStorage('username');
    const userId = getFromLocalStorage('userId');
    
    let decodedToken = null;
    if (token) {
        decodedToken = decodeJWT(token);
    }

    const clientIP = await getClientIP();

    return {
        timestamp: new Date().toISOString(),
        suspiciousPath: path,
        clientIP,
        userAgent: navigator.userAgent,
        username: username || 'anonymous',
        userId: userId || 'none',
        decodedJWT: decodedToken,
        referrer: document.referrer || 'direct',
        screenResolution: `${window.screen.width}x${window.screen.height}`,
    };
}

// Track suspicious route attempts
let suspiciousAttempts: Array<{path: string, timestamp: number}> = [];

export function trackSuspiciousAttempt(path: string): boolean {
    const now = Date.now();
    const fiveMinutesAgo = now - 5 * 60 * 1000;
    
    // Clean old attempts
    suspiciousAttempts = suspiciousAttempts.filter(
        attempt => attempt.timestamp > fiveMinutesAgo
    );
    
    // Add new attempt
    suspiciousAttempts.push({ path, timestamp: now });
    
    // Return true if more than 3 suspicious attempts in 5 minutes
    return suspiciousAttempts.length > 3;
}

export function clearSuspiciousAttempts() {
    suspiciousAttempts = [];
}

// Send email alert directly from frontend
export async function sendSecurityEmail(alertData: any): Promise<boolean> {
    try {
        const emailParams = {
            to_email: ALERT_EMAIL,
            subject: `🚨 Security Alert: ${alertData.suspiciousPath} accessed from ${alertData.clientIP}`,
            message: `
🚨 SECURITY ALERT: Suspicious Path Access Detected

Timestamp: ${alertData.timestamp}
Suspicious Path: ${alertData.suspiciousPath}

Client Information:
- IP Address: ${alertData.clientIP}
- User Agent: ${alertData.userAgent}
- Screen Resolution: ${alertData.screenResolution}
- Referrer: ${alertData.referrer}

User Information:
- Username: ${alertData.username}
- User ID: ${alertData.userId}

Decoded JWT:
${JSON.stringify(alertData.decodedJWT, null, 2)}

---
This alert was automatically generated by your security monitoring system.
            `,
            suspicious_path: alertData.suspiciousPath,
            client_ip: alertData.clientIP,
            user_agent: alertData.userAgent,
            username: alertData.username,
            user_id: alertData.userId,
            timestamp: alertData.timestamp,
            referrer: alertData.referrer,
            screen_resolution: alertData.screenResolution,
            decoded_jwt: JSON.stringify(alertData.decodedJWT, null, 2),
        };

        await emailjs.send(
            EMAILJS_SERVICE_ID,
            EMAILJS_TEMPLATE_ID,
            emailParams
        );

        console.log('✅ Security alert email sent successfully');
        return true;
    } catch (error) {
        console.error('❌ Failed to send security alert email:', error);
        return false;
    }
}
